var F5_env = {
  '#envTSLOGsss4808': '60915200',
  ALLUSERSPROFILE: 'C:\\ProgramData',
  APPDATA: 'C:\\Users\\Newbee\\AppData\\Roaming',
  'asl.log': 'Destination=file',
  ChocolateyInstall: 'C:\\ProgramData\\chocolatey',
  ChocolateyLastPathUpdate: 'Fri Oct 20 00:01:38 2017',
  ChocolateyToolsLocation: 'C:\\tools',
  CommonProgramFiles: 'C:\\Program Files\\Common Files',
  'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
  CommonProgramW6432: 'C:\\Program Files\\Common Files',
  COMPUTERNAME: 'NEWBEE-PC',
  ComSpec: 'C:\\Windows\\system32\\cmd.exe',
  ELECTRON_NO_ASAR: '1',
  ESET_OPTIONS: ' ',
  FP_NO_HOST_CHECK: 'NO',
  GOOGLE_API_KEY: 'AIzaSyAQfxPJiounkhOjODEO5ZieffeBv6yft2Q',
  HOMEDRIVE: 'C:',
  HOMEPATH: '\\Users\\Newbee',
  ILBDIR: 'C:\\Program Files (x86)\\Common Files\\Autodesk Shared\\Materials\\',
  LOCALAPPDATA: 'C:\\Users\\Newbee\\AppData\\Local',
  LOGONSERVER: '\\\\NEWBEE-PC',
  NODE_ENV: 'development',
  NUMBER_OF_PROCESSORS: '8',
  OneDrive: 'E:\\Newbee\\OneDrive',
  OS: 'Windows_NT',
  Path:
    'C:\\Programs\\Python\\Python35-32\\Scripts\\;C:\\Programs\\Python\\Python35-32\\;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\100\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\100\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\100\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\100\\Tools\\Binn\\VSShell\\Common7\\IDE\\;C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\Common7\\IDE\\PrivateAssemblies\\;C:\\Program Files (x86)\\Microsoft SQL Server\\100\\DTS\\Binn\\;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Program Files\\TortoiseSVN\\bin;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\ProgramData\\chocolatey\\bin;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\LLVM\\bin;C:\\Programs\\bin;C:\\Programs\\nodejs\\;C:\\Programs\\Git\\cmd;C:\\Programs\\Git\\mingw64\\bin;C:\\Programs\\Git\\usr\\bin;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Users\\Newbee\\AppData\\Roaming\\npm',
  PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW',
  PROCESSOR_ARCHITECTURE: 'AMD64',
  PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel',
  PROCESSOR_LEVEL: '6',
  PROCESSOR_REVISION: '3c03',
  ProgramData: 'C:\\ProgramData',
  ProgramFiles: 'C:\\Program Files',
  'ProgramFiles(x86)': 'C:\\Program Files (x86)',
  ProgramW6432: 'C:\\Program Files',
  PSModulePath: 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\',
  PUBLIC: 'C:\\Users\\Public',
  SESSIONNAME: 'Console',
  SystemDrive: 'C:',
  SystemRoot: 'C:\\Windows',
  TEMP: 'C:\\Users\\Newbee\\AppData\\Local\\Temp',
  TMP: 'C:\\Users\\Newbee\\AppData\\Local\\Temp',
  USERDOMAIN: 'Newbee-PC',
  USERNAME: 'Newbee',
  USERPROFILE: 'C:\\Users\\Newbee',
  VS110COMNTOOLS:
    'C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\Common7\\Tools\\',
  VS120COMNTOOLS:
    'C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\Common7\\Tools\\',
  VS140COMNTOOLS:
    'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\',
  VSCODE_CWD: 'C:\\Program Files\\Microsoft VS Code',
  VSCODE_IPC_HOOK:
    '\\\\.\\pipe\\702f3f1f37616c69313fb347a3cbf539-1.19.3-main-sock',
  VSCODE_LOGS:
    'C:\\Users\\Newbee\\AppData\\Roaming\\Code\\logs\\20180204T162019',
  VSCODE_NLS_CONFIG: '{"locale":"zh-cn","availableLanguages":{"*":"zh-cn"}}',
  VSCODE_NODE_CACHED_DATA_DIR_8052:
    'C:\\Users\\Newbee\\AppData\\Roaming\\Code\\CachedData\\7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba',
  VSCODE_PID: '8052',
  windir: 'C:\\Windows',
  windows_tracing_flags: '3',
  windows_tracing_logfile: 'C:\\BVTBin\\Tests\\installpackage\\csilogfile.log'
};

var node_env = {
  '#envTSLOGsss4808': '60915200',
  ALLUSERSPROFILE: 'C:\\ProgramData',
  APPDATA: 'C:\\Users\\Newbee\\AppData\\Roaming',
  'asl.log': 'Destination=file',
  ChocolateyInstall: 'C:\\ProgramData\\chocolatey',
  ChocolateyLastPathUpdate: 'Fri Oct 20 00:01:38 2017',
  ChocolateyToolsLocation: 'C:\\tools',
  CommonProgramFiles: 'C:\\Program Files\\Common Files',
  'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
  CommonProgramW6432: 'C:\\Program Files\\Common Files',
  COMPUTERNAME: 'NEWBEE-PC',
  ComSpec: 'C:\\Windows\\system32\\cmd.exe',
  ELECTRON_NO_ASAR: '1',
  ESET_OPTIONS: ' ',
  FP_NO_HOST_CHECK: 'NO',
  GOOGLE_API_KEY: 'AIzaSyAQfxPJiounkhOjODEO5ZieffeBv6yft2Q',
  HOMEDRIVE: 'C:',
  HOMEPATH: '\\Users\\Newbee',
  ILBDIR: 'C:\\Program Files (x86)\\Common Files\\Autodesk Shared\\Materials\\',
  LOCALAPPDATA: 'C:\\Users\\Newbee\\AppData\\Local',
  LOGONSERVER: '\\\\NEWBEE-PC',
  NODE_ENV: 'development',
  NUMBER_OF_PROCESSORS: '8',
  OneDrive: 'E:\\Newbee\\OneDrive',
  OS: 'Windows_NT',
  Path:
    'C:\\Programs\\Python\\Python35-32\\Scripts\\;C:\\Programs\\Python\\Python35-32\\;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\100\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\100\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\100\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\100\\Tools\\Binn\\VSShell\\Common7\\IDE\\;C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\Common7\\IDE\\PrivateAssemblies\\;C:\\Program Files (x86)\\Microsoft SQL Server\\100\\DTS\\Binn\\;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Program Files\\TortoiseSVN\\bin;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\ProgramData\\chocolatey\\bin;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\LLVM\\bin;C:\\Programs\\bin;C:\\Programs\\nodejs\\;C:\\Programs\\Git\\cmd;C:\\Programs\\Git\\mingw64\\bin;C:\\Programs\\Git\\usr\\bin;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Users\\Newbee\\AppData\\Roaming\\npm',
  PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW',
  PROCESSOR_ARCHITECTURE: 'AMD64',
  PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel',
  PROCESSOR_LEVEL: '6',
  PROCESSOR_REVISION: '3c03',
  ProgramData: 'C:\\ProgramData',
  ProgramFiles: 'C:\\Program Files',
  'ProgramFiles(x86)': 'C:\\Program Files (x86)',
  ProgramW6432: 'C:\\Program Files',
  PSModulePath: 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\',
  PUBLIC: 'C:\\Users\\Public',
  SESSIONNAME: 'Console',
  SystemDrive: 'C:',
  SystemRoot: 'C:\\Windows',
  TEMP: 'C:\\Users\\Newbee\\AppData\\Local\\Temp',
  TMP: 'C:\\Users\\Newbee\\AppData\\Local\\Temp',
  USERDOMAIN: 'Newbee-PC',
  USERNAME: 'Newbee',
  USERPROFILE: 'C:\\Users\\Newbee',
  VS110COMNTOOLS:
    'C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\Common7\\Tools\\',
  VS120COMNTOOLS:
    'C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\Common7\\Tools\\',
  VS140COMNTOOLS:
    'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\',
  VSCODE_CWD: 'C:\\Program Files\\Microsoft VS Code',
  VSCODE_IPC_HOOK:
    '\\\\.\\pipe\\702f3f1f37616c69313fb347a3cbf539-1.19.3-main-sock',
  VSCODE_LOGS:
    'C:\\Users\\Newbee\\AppData\\Roaming\\Code\\logs\\20180204T162019',
  VSCODE_NLS_CONFIG: '{"locale":"zh-cn","availableLanguages":{"*":"zh-cn"}}',
  VSCODE_NODE_CACHED_DATA_DIR_8052:
    'C:\\Users\\Newbee\\AppData\\Roaming\\Code\\CachedData\\7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba',
  VSCODE_PID: '8052',
  windir: 'C:\\Windows',
  windows_tracing_flags: '3',
  windows_tracing_logfile: 'C:\\BVTBin\\Tests\\installpackage\\csilogfile.log'
};
